### ISSUE TITLE
Apt vs installing from source ?

### ISSUE THREAD

**Issue by kbumsik** [Wolfie-Home/MQTT-Server#1]
When I tried to install mosquitto from the source then run `./run.sh` I got this:

```
1471104645: mosquitto version 1.4.8 (build date 2016-08-13 16:08:13+0000) starting
1471104645: Config loaded from broker.conf.
1471104645: Opening ipv4 listen socket on port 1883.
1471104645: Opening ipv6 listen socket on port 1883.
^C1471104655: mosquitto version 1.4.8 terminating

```

It looks okay when I installed it from apt-get.

**Comment by cjackie** [comment]
Yes, it is better to install mosquitto via APT....
I have cleaned up a bit.

**Comment by kbumsik** [comment]
Cool. I reviewed the master branch.
The following line should be added before `sudo apt-get install mosquitto,` otherwise APT will install very old version of mosquitto.
```
sudo wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
sudo apt-key add mosquitto-repo.gpg.key
cd /etc/apt/sources.list.d/
sudo wget http://repo.mosquitto.org/debian/mosquitto-wheezy.list
sudo apt-get update
```

**Comment by kbumsik** [comment]
Related link: https://mosquitto.org/2013/01/mosquitto-debian-repository/
